// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllServices() {
  return window['go']['main']['App']['GetAllServices']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetOpenOnStart(arg1) {
  return window['go']['main']['App']['SetOpenOnStart'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetProjectDir(arg1) {
  return window['go']['main']['App']['SetProjectDir'](arg1);
}

export function SetServicePort(arg1, arg2) {
  return window['go']['main']['App']['SetServicePort'](arg1, arg2);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
