// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CanInstallServices():Promise<boolean>;

export function GetAllServices():Promise<Array<main.ServiceStatus>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function InstallService(arg1:string):Promise<void>;

export function OpenBrowser():Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetOpenOnStart(arg1:boolean):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function SetProjectDir(arg1:string):Promise<void>;

export function SetServicePort(arg1:string,arg2:number):Promise<void>;

export function StartServer():Promise<main.ServerStatus>;

export function StartService(arg1:string):Promise<void>;

export function StopServer():Promise<main.ServerStatus>;

export function StopService(arg1:string):Promise<void>;

export function UninstallService(arg1:string):Promise<void>;
