// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectSGBD():Promise<Array<main.SGBDInfo>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetStatus():Promise<main.ServerStatus>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function OpenBrowser():Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetOpenOnStart(arg1:boolean):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function StartServer():Promise<main.ServerStatus>;

export function StopServer():Promise<main.ServerStatus>;
