// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectSGBD() {
  return window['go']['main']['App']['DetectSGBD']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetOpenOnStart(arg1) {
  return window['go']['main']['App']['SetOpenOnStart'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
